---
- name: Create the microshift installer file
  ansible.builtin.template:
    src: microshift-installer.toml.j2
    dest: "{{ microshift_generate_iso_folder }}/microshift-installer.toml"
    mode: '0644'
  register: microshift_installer_template

- name: Add the microshift installer blueprint to image builder
  ansible.builtin.command:
    composer-cli blueprints push {{ microshift_generate_iso_folder }}/microshift-installer.toml

- name: Start the ostree ISO build
  ansible.builtin.command: >
    composer-cli -j compose start-ostree --url http://localhost:8085/repo/
     --ref "rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/edge"
     microshift-installer edge-installer
  register: composed_image

- name: Set build id installer
  ansible.builtin.set_fact:
    build_id_installer: "{{ composed_image.stdout | from_json | json_query('[].body.build_id') | first }}"

- name: Wait for image build to complete
  ansible.builtin.command:
    composer-cli -j compose status
  delay: 30
  retries: 200
  changed_when: false
  until:
    (image_build_status.stdout | from_json | json_query(query_finished)) == "FINISHED"
  register: image_build_status
  vars:
    query_running: "[].body.run[?id=='{{ build_id_installer }}']|[0][0].queue_status"
    query_finished: "[].body.finished[?id=='{{ build_id_installer }}']|[0][0].queue_status"
    query_failed: "[].body.failed[?id=='{{ build_id_installer }}']|[0][0].queue_status"

- name: Set fact download the iso path
  set_fact:
    downloaded_iso_path: "{{ microshift_generate_iso_folder }}/{{ build_id_installer }}.iso"

- name: Download the iso
  ansible.builtin.command:
    composer-cli compose image {{ build_id_installer }} --filename {{ downloaded_iso_path }}

- name: Create the microshift installer file
  ansible.builtin.template:
    src: kickstart.ks.j2
    dest: "{{ microshift_generate_iso_folder }}/kickstart.ks"
    mode: '0644'

- name: Create the iso with the kickstart file
  ansible.builtin.command: >
    mkksiso {{ microshift_generate_iso_folder }}/kickstart.ks
      {{ downloaded_iso_path }}
      {{ microshift_generate_iso_folder }}/microshift_installer.iso

- name: Download the iso to the host
  ansible.posix.synchronize:
    mode: pull
    src: "{{ microshift_generate_iso_folder }}/microshift_installer.iso"
    dest: "{{ microshift_generate_iso_localhost_folder }}/{{ microshift_generate_iso_microshift_iso_name }}"
...
